# Generated by Django 6.0.6 on 2026-07-03 23:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(help_text='ISO 4217 currency code (e.g., EUR, USD, GBP)', max_length=3, primary_key=True, serialize=False)),
                ('display_name', models.CharField(help_text="Translation key for currency name (e.g., 'currency.eur')", max_length=100)),
                ('value', models.DecimalField(decimal_places=8, default=Decimal('1'), help_text='Exchange rate relative to the configured base currency (base = 1)', max_digits=20)),
                ('symbol', models.CharField(blank=True, default='', help_text='Currency symbol (e.g., €, $, £)', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'ordering': ['code'],
            },
        ),
    ]
